name: labeler

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  labeler:
    name: labeler
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
